/* XPM */
static char *arrow2x[] = {
  /* width height num_colors chars_per_pixel */
  "    32    32        3            1",
  /* colors */
  "X c #000000",
  ". c #ffffff",
  "  c None",
  /* pixels */
  "XXXX                            ",
  "XXXX                            ",
  "XX..XX                          ",
  "XX..XX                          ",
  "XX....XX                        ",
  "XX....XX                        ",
  "XX......XX                      ",
  "XX......XX                      ",
  "XX........XX                    ",
  "XX........XX                    ",
  "XX..........XX                  ",
  "XX..........XX                  ",
  "XX............XX                ",
  "XX............XX                ",
  "XX..............XX              ",
  "XX..............XX              ",
  "XX................XX            ",
  "XX................XX            ",
  "XX..................XX          ",
  "XX..................XX          ",
  "XX....XX....XXXXXXXXXX          ",
  "XX....XX....XXXXXXXXXX          ",
  "XX..XX  XX....XX                ",
  "XX..XX  XX....XX                ",
  "XXXX    XX....XX                ",
  "XXXX    XX....XX                ",
  "          XX....XX              ",
  "          XX....XX              ",
  "          XX....XX              ",
  "          XX....XX              ",
  "            XXXXXX              ",
  "            XXXXXX              ",
  "0,0"
};